[tool.poetry]
name = "notebooks"
version = "0.1.0"
description = ""
authors = ["kerowak <boiwaq@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
jupyterlab = "^3.3.3"
ipywidgets = "^7.7.0"
scikit-image = "^0.19.2"
ipyfilechooser = "^0.6.0"
m2stitch = "^0.6.0"
common = {path = "../common", develop=true}
improc = {path = "../improc", develop=true}
ilmatic = {path = "../ilmatic", develop=true}
ipympl = "^0.9.1"
pystackreg = "^0.2.6"
napari = "^0.4.16"
PyQt5 = "^5.15.7"
h5py = "^3.7.0"
pybasic-illumination-correction = "^0.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
